DROP TABLE IF EXISTS `artist` CASCADE ;
DROP TABLE IF EXISTS `album` CASCADE ;
DROP TABLE IF EXISTS `genre` CASCADE ;
DROP TABLE IF EXISTS `playlist` CASCADE ;
DROP TABLE IF EXISTS `track` CASCADE ;

CREATE TABLE IF NOT EXISTS `artist` (`id` BIGINT PRIMARY KEY AUTO_INCREMENT, `name` VARCHAR(100) NOT NULL);
CREATE TABLE IF NOT EXISTS `album` (`id` BIGINT PRIMARY KEY AUTO_INCREMENT, `name` VARCHAR(100) NOT NULL, `cover` VARCHAR(100));
CREATE TABLE IF NOT EXISTS `genre` (`id` BIGINT PRIMARY KEY AUTO_INCREMENT, `name` VARCHAR(100) NOT NULL, `description` VARCHAR(250));
CREATE TABLE IF NOT EXISTS `playlist` (`id` BIGINT PRIMARY KEY AUTO_INCREMENT, `name` VARCHAR(100) NOT NULL, `description` VARCHAR(500),`cover` VARCHAR(100));
CREATE TABLE IF NOT EXISTS `track` (`id` BIGINT PRIMARY KEY AUTO_INCREMENT, `name` VARCHAR(100) NOT NULL, `description` VARCHAR(250), `duration` INT NOT NULL, `lyrics` VARCHAR(255));

                                        