DROP TABLE IF EXISTS `artist` CASCADE ;
DROP TABLE IF EXISTS `album` CASCADE ;
DROP TABLE IF EXISTS `genre` CASCADE ;
DROP TABLE IF EXISTS `playlist` CASCADE ;
DROP TABLE IF EXISTS `track` CASCADE ;
DROP TABLE IF EXISTS `user` CASCADE ;
DROP TABLE IF EXISTS `playlist_track` CASCADE ;

CREATE TABLE IF NOT EXISTS artist (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) NOT NULL);
CREATE TABLE IF NOT EXISTS album (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) NOT NULL, artist_id bigint);
CREATE TABLE IF NOT EXISTS genre (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) NOT NULL, description VARCHAR(250));
CREATE TABLE IF NOT EXISTS playlist (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) NOT NULL, description VARCHAR(500), user_id BIGINT);
CREATE TABLE IF NOT EXISTS track (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) NOT NULL, album_id bigint, artist_id bigint, duration INT NOT NULL, genre_id bigint, lyrics VARCHAR(255));
CREATE TABLE IF NOT EXISTS user (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(50) NOT NULL, password VARCHAR(60));
CREATE TABLE IF NOT EXISTS playlist_track (id BIGINT PRIMARY KEY AUTO_INCREMENT, playlist_id BIGINT, track_id BIGINT);

                                        